# Generated by Django 4.2.6 on 2023-11-18 01:56

import compositefk.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_code', models.CharField(max_length=3)),
                ('building_code', models.CharField(max_length=2)),
                ('floor', models.PositiveIntegerField()),
                ('building', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, related_query_name='floors', to='api_printer.building', to_fields={'building': compositefk.fields.LocalFieldValue('building_code'), 'inst': compositefk.fields.LocalFieldValue('inst_code')})),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inst_code', models.CharField(max_length=3)),
                ('building_code', models.CharField(max_length=2)),
                ('floor_code', models.PositiveIntegerField()),
                ('pages_remaining', models.PositiveIntegerField()),
                ('ink_status', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (3, 'Offline'), (4, 'Error'), (5, 'Busy'), (2, 'Maintenance')], default=1)),
                ('floor', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, related_query_name='printers', to='api_printer.floor', to_fields={'building_code': compositefk.fields.LocalFieldValue('building_code'), 'floor': compositefk.fields.LocalFieldValue('floor_code'), 'inst_code': compositefk.fields.LocalFieldValue('inst_code')})),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_printer.modelprinter')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderPrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='local/')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('print_date', models.DateTimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=50)),
                ('pages', models.PositiveIntegerField()),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_printer.printer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_printer.modelprinter')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_printer.institution'),
        ),
    ]
