# Generated by Django 4.2.6 on 2023-12-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_printer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
