# Generated by Django 4.2.6 on 2023-11-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_printer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='inst',
            field=models.IntegerField(choices=[(1, 'Cơ sở 1'), (2, 'Cơ sở 2')], default=1),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
