# Generated by Django 4.2.6 on 2023-12-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_printer', '0002_printer_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprinter',
            name='page_per_min',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
