# Generated by Django 4.2.6 on 2023-11-14 02:49

import compositefk.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_printer', '0002_feature_modelprinter_remove_choice_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_code', models.CharField(max_length=3)),
                ('building_code', models.CharField(max_length=2)),
                ('floor', models.PositiveIntegerField()),
                ('building', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, related_query_name='floors', to='api_printer.building', to_fields={'building': compositefk.fields.LocalFieldValue('building_code'), 'inst': compositefk.fields.LocalFieldValue('inst_code')})),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inst_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('building_code', models.CharField(max_length=2)),
                ('floor_code', models.PositiveIntegerField()),
                ('floor', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, related_query_name='printers', to='api_printer.floor', to_fields={'building_code': compositefk.fields.LocalFieldValue('building_code'), 'floor': compositefk.fields.LocalFieldValue('floor_code'), 'inst_code': compositefk.fields.LocalFieldValue('inst_code')})),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_printer.modelprinter')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='building',
            name='inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_printer.institution'),
        ),
    ]
