# Generated by Django 4.2.6 on 2023-11-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_printer', '0002_alter_building_inst_delete_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature',
            field=models.CharField(blank=True, choices=[('Scan', 'Scan'), ('Print', 'Print'), ('Photocopy', 'Photocopy')], max_length=10, null=True),
        ),
    ]
