# Generated by Django 4.2.6 on 2023-11-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_printer', '0003_building_floor_institution_printer_building_inst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='inst',
            field=models.CharField(max_length=3),
        ),
    ]
