# Generated by Django 4.2.6 on 2023-11-14 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_printer', '0004_alter_building_inst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_printer.institution'),
        ),
    ]
