# Generated by Django 4.2.6 on 2023-11-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_printer', '0005_alter_building_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
