# Generated by Django 4.2.6 on 2023-11-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_printer', '0006_building_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (3, 'Offline'), (4, 'Error'), (5, 'Busy'), (2, 'Maintenance')], default=1),
        ),
    ]
