# Generated by Django 4.2.6 on 2023-11-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_printer', '0007_printer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printer',
            name='inst_code',
            field=models.CharField(max_length=3),
        ),
    ]
