# Generated by Django 4.2.6 on 2023-11-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pages_remaining',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
